version: "3"

services:
  node:
    build: .
    container_name: cashforce
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      JWT_SECRET: secretJWT
      API_HOST: 'node'
      API_PORT: 3000
      NODE_ENV: 'development'
    networks:
      - cashforce_net

  db:
    container_name: cashforce_db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - cashforce_net

networks:
  cashforce_net:
    driver: bridge
